version: '3'

services:

  db:
    build: ./.docker/mysql
    container_name: codeplatform-db
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=codeplatform
    ports:
      - "42333:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1
